# https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md

name: Release

permissions:
  deployments: write
  packages: write

on:
    workflow_run:
        workflows: [Tests]
        types:
            - completed
        branches:
            - main

jobs:
    docker:
        name: "Docker images"
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    # list of Docker images to use as base name for tags
                    images: ghcr.io/myspeedpuzzling/website
                    # generate Docker tags based on the following events/attributes
                    tags: |
                        type=ref,event=branch
                        type=sha

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3

            -   name: Login to GHCR
                if: github.event_name != 'pull_request'
                uses: docker/login-action@v3
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=registry,ref=ghcr.io/myspeedpuzzling/website:buildcache
                    cache-to: type=registry,ref=ghcr.io/myspeedpuzzling/website:buildcache,mode=max
                    build-args: APP_VERSION=${{ github.sha }}

    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        needs:
            - docker
        environment:
            name: prod
            url: https://myspeedpuzzling.com
        steps:
            -   name: Checkout
                uses: actions/checkout@v6

            -   uses: appleboy/ssh-action@v1
                with:
                    host: myspeedpuzzling.com
                    username: ${{ secrets.DEPLOY_USERNAME }}
                    key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
                    script: cd /deployment/speedpuzzling && ./deploy.sh

            -   name: Create Sentry release
                uses: getsentry/action-release@v3
                env:
                    SENTRY_AUTH_TOKEN: "${{ secrets.SENTRY_AUTH_TOKEN }}"
                    SENTRY_ORG: speedpuzzling
                with:
                    environment: prod
                    projects: web

